# Generated by Django 3.2.4 on 2021-06-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название предмета')),
                ('price', models.IntegerField(verbose_name='Цена предмета')),
                ('isActive', models.BooleanField(default=True, verbose_name='IsActive')),
                ('text', models.TextField(verbose_name='Введите описание')),
                ('file', models.ImageField(upload_to='', verbose_name='Загрузить фото')),
            ],
        ),
    ]
