# Generated by Django 3.2.4 on 2021-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название предмета')),
                ('price', models.IntegerField(verbose_name='Цена предмета')),
                ('isActive', models.BooleanField(default=True, verbose_name='IsActive')),
                ('text', models.TextField(verbose_name='Введите описание')),
                ('category', models.CharField(choices=[('Одежда', 'Одежда'), ('Игры', 'Игры')], default='Прочее', max_length=300, verbose_name='Категория')),
                ('file', models.ImageField(upload_to='', verbose_name='Загрузить фото')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Одежда', 'Одежда'), ('Игры', 'Игры')], default='Прочее', max_length=300, verbose_name='Категория'),
        ),
    ]
