# Generated by Django 3.2.4 on 2021-06-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210627_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('tel', models.TextField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('title', models.TextField(verbose_name='Название предмета')),
                ('price_amount', models.IntegerField(verbose_name='Цена предмета')),
                ('amount', models.IntegerField(verbose_name='Количество')),
            ],
        ),
    ]
